import React, { useMemo, useState } from 'react';
import { Alert, Modal, Pressable, Text, View } from 'react-native';
import { useApp, PaymentMethod, Unit } from '@/context/AppContext';
import { Button, Field, ModalShell, styles } from '@/components/AppUi';
import { useColors } from '@/hooks/useColors';
import { money } from '@/lib/format';

export function CustomerModal({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const { addCustomer } = useApp();
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [address, setAddress] = useState('');
  const save = () => { if (!name.trim()) return Alert.alert('Name required', 'Add a customer name to continue.'); addCustomer({ name: name.trim(), phone, address, openingBalance: 0, notes: '' }); setName(''); setPhone(''); setAddress(''); onClose(); };
  return <Modal visible={visible} transparent animationType="slide"><ModalShell title="New customer" onClose={onClose}><Field label="Customer name" value={name} onChangeText={setName} placeholder="e.g. Rahul Kumar" /><Field label="Mobile number" value={phone} onChangeText={setPhone} placeholder="98765 43210" keyboardType="phone-pad" /><Field label="Address" value={address} onChangeText={setAddress} placeholder="Optional" multiline /><Button label="Save customer" onPress={save} /></ModalShell></Modal>;
}

export function ProductModal({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const { addProduct } = useApp();
  const [name, setName] = useState(''); const [selling, setSelling] = useState(''); const [purchase, setPurchase] = useState(''); const [stock, setStock] = useState(''); const [unit, setUnit] = useState<Unit>('Piece');
  const colors = useColors();
  const units: Unit[] = ['Piece', 'Kg', 'Liter', 'Box'];
  const save = () => { if (!name.trim() || !selling) return Alert.alert('Missing details', 'Add a name and selling price.'); addProduct({ name: name.trim(), sku: '', category: 'General', unit, purchasePrice: Number(purchase) || 0, sellingPrice: Number(selling) || 0, stock: Number(stock) || 0, minStock: 5 }); setName(''); setSelling(''); setPurchase(''); setStock(''); onClose(); };
  return <Modal visible={visible} transparent animationType="slide"><ModalShell title="New product" onClose={onClose}><Field label="Product name" value={name} onChangeText={setName} placeholder="e.g. Rice" /><View style={styles.rowWrap}>{units.map((item) => <Pressable key={item} onPress={() => setUnit(item)} style={[styles.pill, { backgroundColor: unit === item ? colors.primary : colors.secondary }]}><Text style={{ color: unit === item ? colors.primaryForeground : colors.secondaryForeground, fontWeight: '700', fontSize: 12 }}>{item}</Text></Pressable>)}</View><Field label="Selling price" value={selling} onChangeText={setSelling} placeholder="0" keyboardType="numeric" /><Field label="Purchase price" value={purchase} onChangeText={setPurchase} placeholder="0" keyboardType="numeric" /><Field label={`Opening stock (${unit})`} value={stock} onChangeText={setStock} placeholder="0" keyboardType="numeric" /><Button label="Save product" onPress={save} /></ModalShell></Modal>;
}

export function ExpenseModal({ visible, onClose }: { visible: boolean; onClose: () => void }) {
  const { addExpense } = useApp();
  const [category, setCategory] = useState('General'); const [amount, setAmount] = useState(''); const [description, setDescription] = useState('');
  const save = () => { if (!amount) return Alert.alert('Amount required', 'Add an expense amount.'); addExpense({ category, amount: Number(amount), description, method: 'Cash' }); setAmount(''); setDescription(''); onClose(); };
  return <Modal visible={visible} transparent animationType="slide"><ModalShell title="Add expense" onClose={onClose}><Field label="Category" value={category} onChangeText={setCategory} placeholder="Rent, electricity, transport" /><Field label="Amount" value={amount} onChangeText={setAmount} placeholder="0" keyboardType="numeric" /><Field label="Description" value={description} onChangeText={setDescription} placeholder="Optional" multiline /><Button label="Save expense" onPress={save} /></ModalShell></Modal>;
}

export function PaymentModal({ visible, customerId, customerName, balance, onClose }: { visible: boolean; customerId: string; customerName: string; balance: number; onClose: () => void }) {
  const { addPayment } = useApp();
  const [amount, setAmount] = useState(''); const [method, setMethod] = useState<PaymentMethod>('Cash');
  const colors = useColors();
  const save = () => { if (!amount || Number(amount) <= 0) return Alert.alert('Amount required', 'Add a payment amount.'); addPayment(customerId, Number(amount), method); setAmount(''); onClose(); };
  return <Modal visible={visible} transparent animationType="slide"><ModalShell title="Record payment" onClose={onClose}><View style={[styles.balanceBox, { backgroundColor: colors.secondary }]}><Text style={{ color: colors.mutedForeground, fontSize: 12 }}>Current balance</Text><Text style={{ color: colors.foreground, fontSize: 25, fontWeight: '800', marginTop: 3 }}>{money(balance)}</Text><Text style={{ color: colors.secondaryForeground, marginTop: 3 }}>{customerName} will receive a receipt</Text></View><Field label="Amount received" value={amount} onChangeText={setAmount} placeholder="0" keyboardType="numeric" /><Text style={[styles.fieldLabel, { color: colors.mutedForeground }]}>Payment method</Text><View style={styles.rowWrap}>{(['Cash', 'UPI', 'Card', 'Bank'] as PaymentMethod[]).map((item) => <Pressable key={item} onPress={() => setMethod(item)} style={[styles.pill, { backgroundColor: method === item ? colors.primary : colors.secondary }]}><Text style={{ color: method === item ? colors.primaryForeground : colors.secondaryForeground, fontWeight: '700', fontSize: 12 }}>{item}</Text></Pressable>)}</View><Button label="Save payment" onPress={save} /></ModalShell></Modal>;
}

export function SaleModal({ visible, onClose, onSaved }: { visible: boolean; onClose: () => void; onSaved?: (saleId: string) => void }) {
  const { products, customers, addSale } = useApp();
  const [customerId, setCustomerId] = useState<string | undefined>(); const [customerName, setCustomerName] = useState('Walk-in customer'); const [productId, setProductId] = useState(''); const [quantity, setQuantity] = useState('1'); const [paid, setPaid] = useState(''); const [method, setMethod] = useState<PaymentMethod>('Cash');
  const colors = useColors();
  const product = products.find((item) => item.id === productId);
  const total = product ? product.sellingPrice * (Number(quantity) || 0) : 0;
  const save = () => { if (!product || Number(quantity) <= 0) return Alert.alert('Add a product', 'Select a product before saving the bill.'); if (Number(quantity) > product.stock) return Alert.alert('Not enough stock', `${product.name} has ${product.stock} ${product.unit} available.`); const sale = addSale({ customerId, customerName, items: [{ productId: product.id, name: product.name, quantity: Number(quantity), unit: product.unit, rate: product.sellingPrice, total }], discount: 0, tax: 0, paid: Number(paid) || 0, paymentMethod: method }); onClose(); onSaved?.(sale.id); };
  return <Modal visible={visible} transparent animationType="slide"><ModalShell title="New sale" onClose={onClose}><Text style={[styles.fieldLabel, { color: colors.mutedForeground }]}>Customer</Text><View style={styles.rowWrap}>{customers.slice(0, 5).map((item) => <Pressable key={item.id} onPress={() => { setCustomerId(item.id); setCustomerName(item.name); }} style={[styles.pill, { backgroundColor: customerId === item.id ? colors.primary : colors.secondary }]}><Text style={{ color: customerId === item.id ? colors.primaryForeground : colors.secondaryForeground, fontWeight: '700', fontSize: 12 }}>{item.name}</Text></Pressable>)}<Pressable onPress={() => { setCustomerId(undefined); setCustomerName('Walk-in customer'); }} style={[styles.pill, { backgroundColor: !customerId ? colors.primary : colors.secondary }]}><Text style={{ color: !customerId ? colors.primaryForeground : colors.secondaryForeground, fontWeight: '700', fontSize: 12 }}>Walk-in</Text></Pressable></View><Text style={[styles.fieldLabel, { color: colors.mutedForeground, marginTop: 9 }]}>Product</Text><View style={styles.productPicker}>{products.filter((item) => item.stock > 0).map((item) => <Pressable key={item.id} onPress={() => setProductId(item.id)} style={[styles.productOption, { borderColor: productId === item.id ? colors.primary : colors.border, backgroundColor: productId === item.id ? colors.secondary : colors.card }]}><Text style={{ color: colors.foreground, fontWeight: '700' }}>{item.name}</Text><Text style={{ color: colors.mutedForeground, fontSize: 12 }}>{money(item.sellingPrice)} / {item.unit}</Text></Pressable>)}</View>{product ? <View style={[styles.saleSummary, { backgroundColor: colors.secondary }]}><Text style={{ color: colors.foreground, fontWeight: '700' }}>{product.name}</Text><Text style={{ color: colors.primary, fontSize: 21, fontWeight: '800' }}>{money(total)}</Text></View> : null}<Field label={`Quantity (${product?.unit ?? 'unit'})`} value={quantity} onChangeText={setQuantity} placeholder="1" keyboardType="numeric" /><Field label="Paid amount" value={paid} onChangeText={setPaid} placeholder="0" keyboardType="numeric" /><Text style={[styles.fieldLabel, { color: colors.mutedForeground }]}>Payment method</Text><View style={styles.rowWrap}>{(['Cash', 'UPI', 'Credit'] as PaymentMethod[]).map((item) => <Pressable key={item} onPress={() => setMethod(item)} style={[styles.pill, { backgroundColor: method === item ? colors.primary : colors.secondary }]}><Text style={{ color: method === item ? colors.primaryForeground : colors.secondaryForeground, fontWeight: '700', fontSize: 12 }}>{item}</Text></Pressable>)}</View><Button label="Save bill" onPress={save} icon="check" /></ModalShell></Modal>;
}