import React, { useState } from 'react';
import { Alert, Pressable, Share, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useApp, Sale } from '@/context/AppContext';
import { Button, Card, EmptyState, Header, Screen, SectionTitle, styles } from '@/components/AppUi';
import { SaleModal } from '@/components/QuickModals';
import { dateLabel, money } from '@/lib/format';
import { useColors } from '@/hooks/useColors';

export default function BillsScreen() {
  const { sales, business } = useApp();
  const [showSale, setShowSale] = useState(false);
  const [selected, setSelected] = useState<Sale | null>(null);
  const colors = useColors();
  return <Screen><Header eyebrow="SALES" title="Bills" right={<Button label="New bill" onPress={() => setShowSale(true)} icon="plus" />} /><Card style={styles.billSummary}><View><Text style={{ color: colors.mutedForeground, fontSize: 12, fontWeight: '700' }}>ALL-TIME SALES</Text><Text style={{ color: colors.foreground, fontSize: 26, fontWeight: '800', marginTop: 4 }}>{money(sales.reduce((sum, item) => sum + item.total, 0))}</Text></View><View style={[styles.metricIcon, { backgroundColor: colors.secondary }]}><Feather name="file-text" size={18} color={colors.primary} /></View></Card><SectionTitle title={`${sales.length} invoices`} />{sales.length ? sales.map((sale) => <Card key={sale.id} onPress={() => setSelected(sale)} style={styles.listCard}><View><Text style={{ color: colors.foreground, fontWeight: '800' }}>{sale.invoiceNo}</Text><Text style={{ color: colors.mutedForeground, fontSize: 12, marginTop: 4 }}>{sale.customerName} · {dateLabel(sale.createdAt)}</Text></View><View style={{ alignItems: 'flex-end' }}><Text style={{ color: colors.foreground, fontWeight: '800' }}>{money(sale.total)}</Text><Text style={{ color: sale.due ? colors.destructive : colors.primary, fontSize: 12, marginTop: 3 }}>{sale.due ? `${money(sale.due)} due` : 'Paid'}</Text></View></Card>) : <EmptyState icon="file-text" title="No bills yet" body="Create a quick bill and your stock and khata will update together." action="Create first bill" onAction={() => setShowSale(true)} />}<SaleModal visible={showSale} onClose={() => setShowSale(false)} />{selected ? <BillDetail sale={selected} business={business} onClose={() => setSelected(null)} /> : null}</Screen>;
}

function BillDetail({ sale, business, onClose }: { sale: Sale; business: { name: string; address: string; phone: string; upiId: string }; onClose: () => void }) {
  const colors = useColors();
  const share = () => Share.share({ title: sale.invoiceNo, message: `Hello ${sale.customerName},\n\nThank you for shopping with ${business.name}.\nInvoice: ${sale.invoiceNo}\nTotal: ${money(sale.total)}\nPaid: ${money(sale.paid)}\nDue: ${money(sale.due)}\n\nThank you!` }).catch(() => Alert.alert('Share unavailable', 'Please try again on your device.'));
  return <View style={[styles.detailPanel, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.detailHeader}><View><Text style={{ color: colors.foreground, fontSize: 20, fontWeight: '800' }}>{sale.invoiceNo}</Text><Text style={{ color: colors.mutedForeground, marginTop: 3 }}>{dateLabel(sale.createdAt)} · {sale.customerName}</Text></View><Pressable onPress={onClose}><Feather name="x" size={20} color={colors.mutedForeground} /></Pressable></View><View style={[styles.invoicePaper, { borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontWeight: '800', fontSize: 17, textAlign: 'center' }}>{business.name}</Text><Text style={{ color: colors.mutedForeground, textAlign: 'center', marginTop: 3 }}>{business.address}</Text>{business.phone ? <Text style={{ color: colors.mutedForeground, textAlign: 'center', marginTop: 2 }}>{business.phone}</Text> : null}<View style={[styles.divider, { backgroundColor: colors.border }]} />{sale.items.map((item) => <View key={item.productId} style={styles.invoiceLine}><Text style={{ color: colors.foreground, flex: 1 }}>{item.name} × {item.quantity}</Text><Text style={{ color: colors.foreground, fontWeight: '700' }}>{money(item.total)}</Text></View>)}<View style={[styles.divider, { backgroundColor: colors.border }]} /><InvoiceLine label="Subtotal" value={money(sale.subtotal)} /><InvoiceLine label="Paid" value={money(sale.paid)} /><InvoiceLine label="Due" value={money(sale.due)} strong /></View><View style={{ flexDirection: 'row', gap: 8, marginTop: 13 }}><Button label="Share bill" onPress={share} icon="share-2" /><Button label="Print preview" onPress={() => Alert.alert('Print preview', 'A clean invoice preview is ready to print from your device.')} variant="secondary" icon="printer" /></View>{business.upiId ? <View style={[styles.upiNote, { backgroundColor: colors.secondary }]}><Feather name="smartphone" size={17} color={colors.primary} /><Text style={{ color: colors.secondaryForeground, flex: 1, fontSize: 12, lineHeight: 18 }}>UPI payments: {business.upiId}{'\n'}Share this bill and ask the customer to pay securely.</Text></View> : null}</View>;
}

function InvoiceLine({ label, value, strong }: { label: string; value: string; strong?: boolean }) { const colors = useColors(); return <View style={styles.invoiceLine}><Text style={{ color: colors.mutedForeground, fontWeight: strong ? '800' : '400' }}>{label}</Text><Text style={{ color: strong ? colors.primary : colors.foreground, fontWeight: '800' }}>{value}</Text></View>; }